import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const apercuPro = localFont({
	src: [
		{
			path: "../fonts/apercu-pro/regular_pro.otf",
			weight: "400",
			style: "normal",
		},
		{
			path: "../fonts/apercu-pro/regular_italic_pro.otf",
			weight: "400",
			style: "italic",
		},
		{
			path: "../fonts/apercu-pro/medium_pro.otf",
			weight: "600",
			style: "normal",
		},
		{
			path: "../fonts/apercu-pro/medium_italic_pro.otf",
			weight: "600",
			style: "italic",
		},
		{
			path: "../fonts/apercu-pro/bold_pro.otf",
			weight: "700",
			style: "normal",
		},
		{
			path: "../fonts/apercu-pro/bold_italic_pro.otf",
			weight: "700",
			style: "italic",
		},
	],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={apercuPro.className}>{children}</body>
		</html>
	);
}
